webwhois/urls.py
#
# Copyright (C) 2015-2024  CZ.NIC, z. s. p. o.
#
# This file is part of FRED.
#
# FRED is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FRED is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FRED.  If not, see <https://www.gnu.org/licenses/>.
#
from django.urls import path
from django.views.i18n import JavaScriptCatalog
from fred_types import RegistryObjectType

from webwhois.views import (
                            BlockObjectFormView,
                            ContactDetailView,
                            DomainDetailView,
                            DownloadEvalFileView,
                            EmailInRegistryView,
                            KeysetDetailView,
                            NssetDetailView,
                            PersonalInfoFormView,
                            PublicResponseNotFoundView,
                            PublicResponsePdfView,
                            PublicResponseView,
                            RegistrarDetailView,
                            RegistrarListView,
                            ResolveHandleTypeView,
                            ScanResultsView,
                            SendPasswordFormView,
                            ServeRecordStatementView,
                            UnblockObjectFormView,
                            WhoisFormView,
)

app_name = 'webwhois'
urlpatterns = [
    path('', WhoisFormView.as_view(), name='form_whois'),
    path('jsi18n/<packages>/', JavaScriptCatalog.as_view(), name='jsi18n'),
    path('object/<handle>/', ResolveHandleTypeView.as_view(), name='registry_object_type'),
    path('contact/<handle>/', ContactDetailView.as_view(), name='detail_contact'),
    path('nsset/<handle>/', NssetDetailView.as_view(), name='detail_nsset'),
    path('keyset/<handle>/', KeysetDetailView.as_view(), name='detail_keyset'),
    path('domain/<handle>/', DomainDetailView.as_view(), name='detail_domain'),
    path('domain/<handle>/scan-results/', ScanResultsView.as_view(), name='scan_results'),
    path('registrar/<handle>/', RegistrarDetailView.as_view(), name='detail_registrar'),
    path('registrars/', RegistrarListView.as_view(), name='registrars'),
    path('registrar-download-evaluation-file/<handle>/', DownloadEvalFileView.as_view(),
         name='download_evaluation_file'),
    path('send-password/', SendPasswordFormView.as_view(), name='form_send_password'),
    path('personal-info/', PersonalInfoFormView.as_view(), name='form_personal_info'),
    path('block-object/', BlockObjectFormView.as_view(), name='form_block_object'),
    path('unblock-object/', UnblockObjectFormView.as_view(), name='form_unblock_object'),
    path('public-response/<public_key>/', PublicResponseView.as_view(), name='public_response'),
    path('public-response/<public_key>/pdf/', PublicResponsePdfView.as_view(), name='public_response_pdf'),
    path('response-not-found/<public_key>/', PublicResponseNotFoundView.as_view(), name='response_not_found'),
    path('email-in-registry/<public_key>/', EmailInRegistryView.as_view(), name='email_in_registry_response'),
    path('verified-record-statement-pdf/contact/<handle>/', ServeRecordStatementView.as_view(),
         name='record_statement_pdf', kwargs={"object_type": RegistryObjectType.CONTACT}),
    path('verified-record-statement-pdf/domain/<handle>/', ServeRecordStatementView.as_view(),
         name='record_statement_pdf', kwargs={"object_type": RegistryObjectType.DOMAIN}),
    path('verified-record-statement-pdf/keyset/<handle>/', ServeRecordStatementView.as_view(),
         name='record_statement_pdf', kwargs={"object_type": RegistryObjectType.KEYSET}),
    path('verified-record-statement-pdf/nsset/<handle>/', ServeRecordStatementView.as_view(),
         name='record_statement_pdf', kwargs={"object_type": RegistryObjectType.NSSET}),
]

webwhois/views/base.py
#
# Copyright (C) 2015-2024  CZ.NIC, z. s. p. o.
#
# This file is part of FRED.
#
# FRED is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FRED is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FRED.  If not, see <https://www.gnu.org/licenses/>.
#
from abc import ABC, abstractmethod
from functools import lru_cache
from typing import Any, Dict, Generic, TypeVar, Union, cast

from django.views.generic.base import TemplateView, View
from fred_types import RegistryObjectType
from grill import References

from ..constants import LogEntryType, LogResult
from ..exceptions import WebwhoisError
from ..settings import LOGGER

ObjectType = TypeVar('ObjectType')


class RegistryObjectView(TemplateView, Generic[ObjectType], ABC):
    """Base class for loading object registry of the handle."""

    log_entry_type = LogEntryType.INFO

    @property
    @abstractmethod
    def object_type(self) -> Union[RegistryObjectType, str]:
        """Return name of the object type this view handles."""

    def load_related_objects(self, context: Dict[str, Any]) -> None:
        """Load objects related to the main registry object and append them into the context."""

    def _make_context(self, obj: ObjectType) -> Dict[str, Any]:
        """Turn object into a context."""
        return {self.object_type: {"detail": obj}}

    @lru_cache  # noqa: B019
    def get_object(self) -> ObjectType:
        """Fetch and return an object from registry.

        Raises:
            WebwhoisError: If the object is not found in registry backend.
        """
        handle = cast(View, self).kwargs["handle"]
        properties = {"handle": handle, "handleType": self.object_type}
        with LOGGER.create(self.log_entry_type, source_ip=cast(View, self).request.META.get('REMOTE_ADDR', ''),
                           properties=properties) as log_entry:
            try:
                obj = self._get_object(handle)
            except WebwhoisError:
                log_entry.result = LogResult.NOT_FOUND
                raise
            except BaseException as error:
                log_entry.result = LogResult.ERROR
                log_entry.properties["exception"] = error.__class__.__name__
                raise
            else:
                log_entry.references = self._get_references(obj)
                log_entry.result = LogResult.SUCCESS
            return obj

    @abstractmethod
    def _get_object(self, handle: str) -> ObjectType:
        """Actually fetches and returns the object from registry.

        Arguments:
            handle: Handle of an object to find.

        Raises:
            WebwhoisError: If the object is not found in registry backend.
        """

    @abstractmethod
    def _get_references(self, obj: ObjectType) -> References:
        """Return log references for the object."""

    def get_context_data(self, handle: str, **kwargs: Any) -> Dict[str, Any]:  # type: ignore[override]
        kwargs.setdefault("handle", handle)
        obj = self.get_object()
        context = {}
        context.update(self._make_context(obj))
        self.load_related_objects(context)
        context.update(kwargs)
        return super().get_context_data(**context)

webwhois/views/form_whois.py
#
# Copyright (C) 2015-2024  CZ.NIC, z. s. p. o.
#
# This file is part of FRED.
#
# FRED is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FRED is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FRED.  If not, see <https://www.gnu.org/licenses/>.
#
from typing import Any, Dict, cast

from django.http import HttpResponse
from django.urls import ResolverMatch, reverse
from django.views.generic import FormView

from webwhois.forms import WhoisForm


class WhoisFormView(FormView):

    template_name = 'webwhois/form_whois.html'
    form_class = WhoisForm

    def get_initial(self) -> Dict[str, Any]:
        data = self.initial.copy()
        data["handle"] = self.request.GET.get("handle")
        return data

    def form_valid(self, form: WhoisForm) -> HttpResponse:
        self.success_url = reverse("webwhois:registry_object_type", kwargs={"handle": form.cleaned_data['handle']},
                                   current_app=cast(ResolverMatch, self.request.resolver_match).namespace)
        return super().form_valid(form)

webwhois/views/registrar.py
#
# Copyright (C) 2015-2023  CZ.NIC, z. s. p. o.
#
# This file is part of FRED.
#
# FRED is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FRED is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FRED.  If not, see <https://www.gnu.org/licenses/>.
#
import random
from contextlib import suppress
from datetime import datetime
from functools import cached_property
from typing import Any, Dict, List, Optional, cast

from django.http import Http404, HttpRequest, StreamingHttpResponse
from django.utils import timezone
from django.utils.translation import gettext as _
from django.views.generic import TemplateView, View
from grill import References
from regal import Registrar, RegistrarCertification
from regal.exceptions import RegistrarDoesNotExist

from ..constants import REGISTRAR
from ..exceptions import WebwhoisError
from ..settings import REGISTRAR_CLIENT, STORAGE
from .base import RegistryObjectView


class RegistrarDetailView(RegistryObjectView[Registrar]):
    """Detail of Registrar."""

    template_name = "webwhois/registrar.html"
    object_type = REGISTRAR

    def _get_object(self, handle: str) -> Registrar:
        try:
            return cast(Registrar, REGISTRAR_CLIENT.get_registrar_info(handle))
        except RegistrarDoesNotExist as error:
            raise WebwhoisError(handle, 'OBJECT_NOT_FOUND', message=_("Registrar not found")) from error

    def _get_references(self, obj: Registrar) -> References:
        """Return log references for the object."""
        return {self.object_type: obj.registrar_id}


def _get_aware_now() -> datetime:
    """Return aware 'now' datetime regardless of Django settings."""
    now = timezone.now()
    if timezone.is_naive(now):
        now = timezone.make_aware(now)
    return now


class RegistrarListView(TemplateView):
    """Mixin for a list of registrars.

    @cvar group_name: Name of the registrar group to filter results.
    """

    template_name = "webwhois/registrar_list.html"
    group_name: Optional[str] = None

    def __init__(self, *args: Any, **kwargs: Any):
        super().__init__(*args, **kwargs)
        # Caches for backend responses
        self._groups: Optional[Dict[str, List[str]]] = None

    @cached_property
    def all_registrar_handles(self) -> List[str]:
        """Return a list of all registrar handles."""
        return cast(List[str], REGISTRAR_CLIENT.get_registrar_handles())

    def get_registrars(self) -> List[Registrar]:
        """Return a list of registrars to be displayed.

        Results are filtered according to `group_name` attribute.
        """
        if self.group_name:
            groups = self.get_groups()
            if self.group_name not in groups:
                raise Http404('Registrar group {} not found.'.format(self.group_name))
            members = groups[self.group_name]
        else:
            members = self.all_registrar_handles
        return [REGISTRAR_CLIENT.get_registrar_info(handle) for handle in members]

    def get_groups(self) -> Dict[str, List[str]]:
        """Return dictionary of registrar groups."""
        if self._groups is None:
            groups: Dict[str, List[str]] = {g: [] for g in REGISTRAR_CLIENT.get_registrar_groups()}
            for handle in self.all_registrar_handles:
                for group in REGISTRAR_CLIENT.get_registrar_groups_membership(handle):
                    groups[group].append(handle)
            self._groups = groups
        return self._groups

    def get_certification(self, handle: str) -> Optional[RegistrarCertification]:
        """Return dictionary of active registrar certifications."""
        now = _get_aware_now()
        for certification in cast(List[RegistrarCertification], REGISTRAR_CLIENT.get_registrar_certifications(handle)):
            if certification.valid_from <= now and (certification.valid_to is None or certification.valid_to > now):
                return certification
        return None

    def get_registrar_context(self, registrar: Registrar) -> Dict[str, Any]:
        """Return context for a registrar."""
        certification = self.get_certification(registrar.registrar_handle)
        score = certification.classification if certification else 0
        context = {REGISTRAR: registrar, "cert": certification, "score": score}
        return context

    def sort_registrars(self, registrars: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Sort context data of registrars.

        Registrars are randomized, but sorted according to their certification score.
        """
        # Randomize order of the list of registrars and than sort it by score.
        rand = random.SystemRandom()
        rand.shuffle(registrars)
        return sorted(registrars, key=lambda row: cast(int, row["score"]), reverse=True)

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        registrars = []
        for reg in self.get_registrars():
            registrars.append(self.get_registrar_context(reg))

        kwargs.setdefault("groups", self.get_groups())
        kwargs.setdefault("registrars", self.sort_registrars(registrars))
        return super().get_context_data(**kwargs)


class DownloadEvalFileView(View):
    def get(self, request: HttpRequest, handle: str) -> StreamingHttpResponse:
        certification = self.get_certification(handle)
        if certification:
            try:
                with STORAGE.open(certification.file_id) as file:
                    response = StreamingHttpResponse(file, content_type=file.mimetype)
                    response["Content-Disposition"] = 'inline; filename="{}"'.format(file.name)
                    return response
            except FileNotFoundError as error:
                raise Http404("File not found") from error
        raise Http404("Certification not found")

    def get_certification(self, handle: str) -> Optional[RegistrarCertification]:
        """Return registrar certification."""
        now = _get_aware_now()
        with suppress(RegistrarDoesNotExist):
            for certification in cast(List[RegistrarCertification],
                                      REGISTRAR_CLIENT.get_registrar_certifications(handle)):
                if certification.valid_from <= now and (certification.valid_to is None or certification.valid_to > now):
                    return certification
        return None

webwhois/templates/webwhois/block_main.html
{% extends "webwhois/base.html" %}
{% load i18n %}

{% block content %}
    <div id="whois">
        {% block webwhois_main %}

            {% block webwhois_header %}
                <h1>{% trans "Search in the Registry (Whois)" %}</h1>
                <p>
                    {% trans "Search results for handle" %} <strong class="text-primary">{{ handle }}</strong>:
                </p>
            {% endblock webwhois_header %}

            {% block webwhois_content %}{% endblock webwhois_content %}

            {% block webwhois_footer %}
                <a class="btn btn-primary mt-5" href="{% url "webwhois:form_whois" %}">
                    {% trans "New search in the registry" %}
                </a>
            {% endblock webwhois_footer %}

        {% endblock webwhois_main %}
    </div>
{% endblock content %}

webwhois/templates/webwhois/domain.html
{% extends "webwhois/block_main.html" %}
{% load i18n static webwhois_filters %}

{% block title %}{% trans "Domain name" context "fullname" %} {{ handle }} - {{ block.super }}{% endblock %}

{% block webwhois_header %}
    {{ block.super }}
    <h2>{% trans "Domain name details" %}</h2>
{% endblock webwhois_header %}

{% block webwhois_content %}
    <div class="table-responsive" id="domain_record">
        <table class="result domain table table-bordered">
            <tr>
                <th>{% trans "Domain name" context "fullname" %}</th>
                <td>
                    {% if domain.detail.fqdn|idn_decode == domain.detail.fqdn %}
                        <span class="handle">{{ domain.detail.fqdn }}</span>
                    {% else %}
                        <span class="idn-handle">{{ domain.detail.fqdn|idn_decode }}</span>
                        (<span class="handle">{{ domain.detail.fqdn }}</span>)
                    {% endif %}
                </td>
            </tr>
            {% if 'deleteCandidate' not in domain.flags %}
                <tr>
                    <th>{% trans "Registered since" %}</th>
                    <td class="registered-since">{{ domain.detail.events.registered.timestamp|date:"SHORT_DATE_FORMAT" }}</td>
                </tr>
                <tr>
                    <th>{% trans "Last update date" %}</th>
                    <td class="last-update-date">
                        {% if domain.detail.events.updated %}
                            {{ domain.detail.events.updated.timestamp|date:"SHORT_DATE_FORMAT" }}
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th>{% trans "Expiration date" %}</th>
                    <td class="expiration-date">{{ domain.detail.expires_at|date:"SHORT_DATE_FORMAT" }}</td>
                </tr>
                {% if domain.detail.validation_expires_at %}
                    <tr>
                        <th>{% trans "Validation expiration date" %}</th>
                        <td class="validated-to">{{ domain.detail.validation_expires_at|date:"SHORT_DATE_FORMAT" }}</td>
                    </tr>
                {% endif %}
                <tr>
                    <th>{% trans "Holder" %}</th>
                    <td class="holder">
                        <a href="{% url "webwhois:detail_contact" handle=domain.detail.registrant.handle %}">{{ domain.detail.registrant.handle }}</a>
                        <span>{{ domain.detail.registrant.organization|default:domain.detail.registrant.name }}</span>
                    </td>
                </tr>
                <tr>
                    <th>{% trans "Administrative contact" %}</th>
                    <td class="admins">
                        {% for admin in domain.detail.administrative_contacts %}
                            <div>
                                <a href="{% url "webwhois:detail_contact" handle=admin.handle %}">{{ admin.handle }}</a>
                                <span>{{ admin.organization|default:admin.name }}</span>
                            </div>
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <th>{% trans "Sponsoring registrar" %}</th>
                    <td class="sponsoring-registrar">
                        <a href="{% url "webwhois:detail_registrar" handle=domain.registrar.registrar_handle %}">{{ domain.registrar.registrar_handle }}</a>
                        <span>{{ domain.registrar.name }}</span>
                        <span>{% spaceless %}
                            {% blocktrans with date=domain.detail.events.transferred.timestamp|default:domain.detail.events.registered.timestamp trimmed %}
                                since {{ date }}
                            {% endblocktrans %}
                        {% endspaceless %}</span>
                    </td>
                </tr>
                <tr>
                    <th>{% trans "Secured by DNSSEC" %}</th>
                    <td class="dnssec">
                        {% if domain.detail.keyset %}
                            <img src='{% static "webwhois/img/icon-yes.gif" %}' alt='{% trans "Yes" %}'>
                        {% else %}
                            <img src='{% static "webwhois/img/icon-no.gif" %}' alt='{% trans "No" %}'>
                        {% endif %}
                    </td>
                </tr>
            {% endif %}
            <tr>
                <th>{% trans "Status" %}</th>
                <td class="status">
                    {% for flag in domain.flags %}
                         <div>{{ flag|state_flag_description }}</div>
                    {% endfor %}
                </td>
            </tr>
        </table>
    </div>
    {% if nsset %}
        <div id="nsset_record">
            {% include "webwhois/include/nsset_detail.html" %}
        </div>
    {% endif %}
    {% if keyset %}
        <div id="keyset_record">
            {% include "webwhois/include/keyset_detail.html" %}
        </div>
    {% endif %}
    {% if 'deleteCandidate' not in domain.flags %}
        {% url "webwhois:record_statement_pdf" object_type="domain" handle=domain.detail.fqdn as record_statement_pdf_url %}
        {% include "webwhois/include/record_statement_link.html" %}
    {% endif %}
{% endblock webwhois_content %}

{% block webwhois_footer %}
    {% if scan_results_link %}
        <p>
            <a href="{{ scan_results_link }}">{% trans "Results of DNSSEC automatic management scans" %}</a>
        </p>
    {% endif %}
    {{ block.super }}
{% endblock webwhois_footer %}

webwhois/templates/webwhois/form_block_object.html
{% extends "webwhois/form_public_request.html" %}
{% load i18n %}

{% block title %}{% trans "Request to enable enhanced object security" %} - {{ block.super }}{% endblock %}

{% block webwhois_header %}
    <h1>{% trans "Request to enable enhanced object security" %}</h1>
    <p>
        {% trans "After you submit this request, the register will prohibit, according to your choice, to transfer your object or to modify its details (changes, removals)." %}
    </p>
    <p>
        {% trans "Then the register will send an informational email to the holder in case of domains, to the contact itself, or to all technical contacts in case of nameserver sets or key sets." %}
    </p>
{% endblock webwhois_header %}

{% block webwhois_content %}
    <div id="form_wrapper">
        <h2>{% trans "Request form to enable enhanced object security" %}</h2>
        <div id="public_request_forms">
            <form id="block_object_form" action="{% url "webwhois:form_block_object" %}" method="post" class="webwhois-public-request w-100">
                {% csrf_token %}

                {% include "webwhois/include/public_request_form_fields.html" %}

                <button class="btn btn-primary d-block ms-auto mt-5" id="submit_button" type="submit">
                    {% trans "Send" %}
                </button>
            </form>
        </div>
    </div>
{% endblock webwhois_content %}

webwhois/templates/webwhois/keyset.html
{% extends "webwhois/block_main.html" %}
{% load i18n %}

{% block title %}{% trans "Keyset" %} {{ handle }} - {{ block.super }}{% endblock %}

{% block webwhois_header %}
    {{ block.super }}
    <h2>{% trans "Key set details" %}</h2>
{% endblock webwhois_header %}

{% block webwhois_content %}
    {% include "webwhois/include/keyset_detail.html" %}
    {% url "webwhois:record_statement_pdf" object_type="keyset" handle=keyset.detail.keyset_handle as record_statement_pdf_url %}
    {% include "webwhois/include/record_statement_link.html" %}
{% endblock webwhois_content %}

webwhois/templates/webwhois/nsset.html
{% extends "webwhois/block_main.html" %}
{% load i18n %}

{% block title %}{% trans "Nsset" %} {{ handle }} - {{ block.super }}{% endblock %}

{% block webwhois_header %}
    {{ block.super }}
    <h2>{% trans "Name server set (DNS) details" %}</h2>
{% endblock webwhois_header %}

{% block webwhois_content %}
    {% include "webwhois/include/nsset_detail.html" %}
    {% url "webwhois:record_statement_pdf" object_type="nsset" handle=nsset.detail.nsset_handle as record_statement_pdf_url %}
    {% include "webwhois/include/record_statement_link.html" %}
{% endblock webwhois_content %}

webwhois/templates/webwhois/scan_results.html
{% extends "webwhois/block_main.html" %}
{% load i18n static keyset_filters %}

{% block title %}{% trans "Scan results" %} {{ handle }} - {{ block.super }}{% endblock %}

{% block extrahead %}
    <script type="text/javascript" src="{% url 'webwhois:jsi18n' packages='webwhois' %}"></script>
    <script type="text/javascript" src="{% static "webwhois/js/main.js" %}"></script>
    <link rel="stylesheet" href="{% static 'webwhois/css/scan_results.css' %}" type="text/css" />
{% endblock %}

{% block content %}
    <div id="whois-cdns" class="table-responsive">
        {% block webwhois_main %}
            {% block webwhois_header %}
                <h1>{% trans "Results of DNSSEC automatic management scans" %}</h1>
                {% block webwhois_scan_results_header %}{% endblock %}
                <p>
                    {% trans "Results of DNSSEC automatic management scans for the domain" %} <a href="{% url 'webwhois:detail_domain' handle=handle %}" title="{% trans 'Domain name details' %}">{{ handle }}</a>:
                </p>
            {% endblock webwhois_header %}
            {% block webwhois_content %}
                <div class="table-scrollable">
                    <table class="result scan-table table table-bordered table-fixed break-word">
                        <thead>
                            <tr>
                                <th>{% trans "Date and time" %}</th>
                                <th>{% trans "Name server" %}</th>
                                <th>{% trans "Scan status" %}</th>
                                <th>{% trans "Flags" %}</th>
                                <th>{% trans "Algorithm" %}</th>
                                <th>{% trans "Protocol" %}</th>
                                <th>{% trans "Public key" %}</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for result in scan_results %}
                            <tr>
                                <td data-label="{% trans "Date and time" %}">{{ result.scan_at|date:"SHORT_DATETIME_FORMAT" }}</td>
                                <td data-label="{% trans "Name server" %}">
                                    <div class="name-server-wrapper">
                                        <span>{{ result.nameserver|default:'' }}</span>
                                        {% if result.nameserver_ip|length > 0 %}
                                            <span>({{ result.nameserver_ip }})</span>
                                        {% endif  %}
                                    </div>
                                </td>
                                <td data-label="{% trans "Status" %}">
                                    <div class="status-wrapper">
                                        <span>{{ result.cdnskey.status.value }}</span>
                                        <span
                                            tabindex="0"
                                            data-text="{{ result.cdnskey.status.label }}"
                                            class="tooltip question-mark">
                                        </span>
                                    </div>
                                </td>
                                <td data-label="{% trans "Flags" %}">
                                    {% if result.cdnskey.public_key %}
                                        {{ result.cdnskey.flags }}
                                        ({{ result.cdnskey.flags|dnskey_flag_labels }})
                                    {% endif %}
                                </td>
                                <td
                                    data-label="{% trans "Algorithm" %}">
                                        {% if result.cdnskey.public_key %}
                                            {{ result.cdnskey.alg.value }} ({{ result.cdnskey.alg.label }})
                                        {% endif %}
                                </td>
                                <td data-label="{% trans "Protocol" %}">
                                    {% if result.cdnskey.proto %}
                                        {{ result.cdnskey.proto }}
                                        {% if result.cdnskey.proto == 3 %}
                                            (<span>DNSSEC</span>)
                                        {% endif %}
                                    {% endif %}
                                </td>
                                <td data-label="{% trans "Public key" %}">
                                    {% if result.cdnskey.public_key %}
                                        <div class="public-key-wrapper">
                                            <p class="public-key">{{ result.cdnskey.public_key }}</p>
                                            <div class="public-key-actions">
                                                <span
                                                    tabindex="0"
                                                    class="tooltip public-key-view btn btn-outline-primary btn-sm"
                                                    data-text="{{ result.cdnskey.public_key }}">
                                                    {% trans "View" %}
                                                </span>
                                                <button
                                                    class="public-key-copy btn btn-outline-dark btn-sm"
                                                    data-public_key="{{ result.cdnskey.public_key }}">
                                                    {% trans "Copy" %}
                                                </button>
                                            </div>
                                        </div>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endblock webwhois_content %}

            {% block webwhois_footer %}
            {% endblock webwhois_footer %}
        {% endblock webwhois_main %}
    </div>
{% endblock content %}